services:
  flask-app:
    build:
      context: .
      dockerfile: ./flask-app/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - SECRET_KEY=dev-secret-key-change-in-production
      - CHAINLIT_SERVICE_URL=http://chainlit-service:8080
      - DATABASE_PATH=/app/data/app.db
      - FLASK_ENV=development
      - PORT=8080
    volumes:
      - flask_data:/app/data
    depends_on:
      - chainlit-service
    restart: unless-stopped

  chainlit-service:
    build:
      context: .
      dockerfile: ./chainlit-service/Dockerfile
    ports:
      - "8000:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=8080
    restart: unless-stopped

volumes:
  flask_data: 